config/routes.rb
ModbiblioUcc::Application.routes.draw do
  resources :requests

  resources :authors

  resources :books

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get 'sign_up' => 'users#new', :as => 'sign_up'
  root :to => "books#index"
  resources :users
  resources :sessions

  get "users/show"

  get "users/index"

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  belongs_to :copy
  
  validates_presence_of :user
  validates_presence_of :copy
  validates_presence_of :request_date
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  # GET /requests
  # GET /requests.xml
  load_and_authorize_resource
  def index
    @requests = Request.all
    @title = "Listado de Solicitudes"
    @header = @title
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /requests/1
  # GET /requests/1.xml
  def show
    @request = Request.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /requests/new
  # GET /requests/new.xml
  def new
    @request = Request.new
    @title = "Reservar Libro"
    @header = @title
    @request.user = current_user
    @request.copy = Copy.find_by_code(params[:code])
    @request.request_date = Date.today

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
    @title = "Editar prestamo"
    @header = @title
  end

  # POST /requests
  # POST /requests.xml
  def create
    @request = Request.new(params[:request])
    @request_temp = Request.find(:all, :conditions => "copy_id ='#{@request.copy_id}' and request_date = '#{@request.request_date}'")

    if @request_temp.blank?
      respond_to do |format|
        if @request.save
          if @request.activated?
            format.html { redirect_to(@request, :notice => 'Prestamo realizado con exito.') }
          else
            format.html { redirect_to(@request, :notice => 'Reservacion realizada') }
          end
        else
          format.html { render :action => "new" }
        end
      end
    else
      flash[:error] = "Libro reservado para esa fecha"
      render :action => 'new'
    end
  end

  # PUT /requests/1
  # PUT /requests/1.xml
  def update
    @request = Request.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        format.html { redirect_to(@request, :notice => 'Prestamo actualizado.') }
      else
        format.xml  { render :xml => @request.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.xml
  def destroy
    @request = Request.find(params[:id])
    @request.destroy

    respond_to do |format|
      format.html { redirect_to(requests_url) }
    end
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= semantic_form_for @request do |f| %>
  <% f.inputs do %>
    <%= f.input :user, :label => "Usuario" %>
    <%= f.input :copy, :label => "Codigo de Copia", :as => :select, :collection => Copy.order(:code), :label_method => :code %>
    <%= f.input :request_date, :label => "Fecha de Solicitud" %>
    <% if can? :update, @request %>
      <%= f.input :activated, :label => "Activado" %> 
      <%= f.input :delivery_date, :label => "Fecha de Entrega" %> 
      <%= f.input :return_date, :label => "Fecha de Devolucion" %>
    <% end %>
  <% end %>
  <%= f.buttons do %>
    <%= f.commit_button :label => "Enviar"%>
  <% end %>
<% end %>

app/views/requests/edit.html.erb
<%= render 'form' %>

<%= link_to 'Mostrar', @request %> |
<%= link_to 'Regresar', requests_path %>

app/views/requests/index.html.erb
<table>
  <tr>
    <th>Nombre de Usuario</th>
    <th>Ejemplar</th>
    <th>Titulo</th>
    <th>Activado</th>
    <th>Fecha de reserva</th>
    <th>Fecha de entrega</th>
    <th>Fecha de devolución</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @requests.each do |request| %>
  <tr>
    <td><%= request.user.username %></td>
    <td><%= request.copy.code %></td>
    <td><%= request.copy.book.title %></td>
    <td><%= request.activated %></td>
    <td><%= request.request_date %></td>
    <td><%= request.delivery_date %></td>
    <td><%= request.return_date %></td>
    <td><%= link_to 'Mostrar', request %></td>
    <td><%= link_to 'Editar', edit_request_path(request) %></td>
    <td><%= link_to 'Eliminar', request, :confirm => 'Esta seguro?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo Prestamo', new_request_path %> | <%= link_to "Pagina Principal", books_path %>

app/views/requests/new.html.erb
<%= render 'form' %>

<%= link_to 'Regresar', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Usuario:</b>
  <%= @request.user.username %>
</p>

<p>
  <b>Copy:</b>
  <%= @request.copy_id %>
</p>

<p>
  <b>Titulo:</b>
  <%= @request.copy.book.title %>
</p>

<p>
  <b>Activo:</b>
  <%= @request.activated %>
</p>

<p>
  <b>Fecha de Solicitud:</b>
  <%= @request.request_date %>
</p>

<p>
  <b>Fecha de Entrega:</b>
  <%= @request.delivery_date %>
</p>

<p>
  <b>Fecha de devolucion:</b>
  <%= @request.return_date %>
</p>


<%= link_to 'Editar', edit_request_path(@request) %> |
<%= link_to 'Regresar', requests_path %> |
<%= link_to 'Página Principal', books_path %>