config/routes.rb
ModbiblioUcc::Application.routes.draw do
  resources :requests

  resources :authors

  resources :books

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get 'sign_up' => 'users#new', :as => 'sign_up'
  root :to => "books#index"
  resources :users
  resources :sessions

  get "users/show"

  get "users/index"

end

app/models/book.rb
class Book < ActiveRecord::Base
  #attr_accessible :isbn, :title, :editorial, :description
  #
  has_many :authorships
  has_many :authors, :through => :authorships
  has_many :copies, :dependent => :destroy

  validates :title, :uniqueness => true,
    :presence => true
  validates :isbn, :uniqueness => true,
    :presence => true
  validates :editorial, :presence => true

  accepts_nested_attributes_for :copies, :reject_if => :all_blank
  accepts_nested_attributes_for :authors, :reject_if => :all_blank

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource
  def index
    @books = Book.where({:title.matches => "%#{params[:search]}%"} | {:description.matches => "%#{params[:search]}%"}).all
    @title = "Listado de Libros"
    @header = @title
  end

  def show
    @book = Book.find(params[:id])
    @title = "Detalle de Libro"
    @header = @title
  end

  def new
    @book = Book.new
    @title = "Nuevo Libro"
    @header = @title
    3.times { @book.authors.build }
    3.times { @book.copies.build }
  end

  def create
    @book = Book.new(params[:book])
    if @book.save
      flash[:notice] = "Libro creado exitosamente."
      redirect_to @book
    else
      render :action => 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
    @title = "Editar Libro"
    @header = @title
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(params[:book])
      flash[:notice] = "Libro actualizado exitosamente."
      redirect_to book_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Libro eliminado exitosamente."
    redirect_to books_url
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= semantic_form_for @book do |f| %>
  <% f.inputs do %>
    <%= f.input :isbn %>
    <%= f.input :title, :label => "Titulo" %>
    <%= f.input :editorial %>
    <%= f.input :description, :label => "Descripcion", :input_html => { :rows => 5 } %>
    <%= f.input :authors, :label => "Autores Existentes", :as => :select, :collection => Author.order(:name) %>
    <h3>Nuevo Autor(es)</h3>
    <%= f.semantic_fields_for :authors do |builder| %>
      <%= builder.input :name, :label => "Nombre" %>
    <% end %>
    <h3>Ejemplares del libro</h3>
    <%= f.semantic_fields_for :copies do |builder| %>
      <%= builder.input :code, :label => "Código" %>
    <% end %>
  <% end %>
  <% f.buttons do %>
    <%= f.commit_button :label => "Enviar"%>
  <% end %>
<% end %>

app/views/books/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Mostrar", @book %> |
  <%= link_to "Ver Todos", books_path %>
</p>

app/views/books/index.html.erb
Buscar por titulo ó descripción
<%= form_tag books_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Buscar", :name => nil %>
<% end %>
<br />
<table>
  <tr>
    <th>Isbn</th>
    <th>Titulo</th>
    <th>Editorial</th>
    <th>Descripción</th>
    <th>Autor(es)</th>
    <th>Ejemplares</th>
  </tr>
  <% for book in @books %>
    <tr>
      <td><%= book.isbn %></td>
      <td><%= book.title %></td>
      <td><%= book.editorial %></td>
      <td><%= book.description %></td>
      <td>
        <% for author in book.authors %>
          <p><%= author.name %></p>
        <% end %>
      </td>
      <td>
        <% for copy in book.copies %>
          <p><%= copy.code %></p>
          <% if can? :create, Request %>
            <%= link_to "Reservar", new_request_path(:code => copy.code) %>
          <% end %>
        <% end %>
      </td>
      <td><%= link_to "Mostrar", book %></td>
      <% if can? :update, @books %>
        <td><%= link_to "Editar", edit_book_path(book) %></td>
        <td><%= link_to "Eliminar", book, :confirm => 'Está seguro?', :method => :delete %></td>
      <% end %>
    </tr>
  <% end %>
</table>
<% if can? :create, @books %>
  <p><%= link_to "Nuevo Libro", new_book_path(book) %> </p>
<% end %>

app/views/books/new.html.erb
<%= render 'form' %>

<p><%= link_to "Regresar a lista de Libros", books_path %></p>

app/views/books/show.html.erb
<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>
<p>
  <strong>Titulo:</strong>
  <%= @book.title %>
</p>
<p>
  <strong>Editorial:</strong>
  <%= @book.editorial %>
</p>
<p>
  <strong>Descripción:</strong>
  <%= @book.description %>
</p>
<p>
  <strong>Autor(es)</strong>
  <% for author in @book.authors %>
    <li><%=h author.name %></li>
  <% end %>
</p>
<p>
  <strong>Ejemplares</strong>
  <% for copy in @book.copies %>
    <li><%=h copy.code %></li>
  <% end %>
</p>
<p>
  <%= link_to "Editar", edit_book_path(@book) %> |
  <%= link_to "Eliminar", @book, :confirm => 'Está seguro?', :method => :delete %> |
  <%= link_to "Ver todos", books_path %>
</p>